// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: common-types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceType int32

const (
	DeviceType_TELTONIKA      DeviceType = 0
	DeviceType_WANWAY         DeviceType = 1
	DeviceType_CONCOX         DeviceType = 2
	DeviceType_HOWEN          DeviceType = 3
	DeviceType_AQUILA         DeviceType = 4
	DeviceType_INTELLITRAC    DeviceType = 5
	DeviceType_QUECLINK_GV200 DeviceType = 6
	DeviceType_QUECLINK_GT500 DeviceType = 7
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "TELTONIKA",
		1: "WANWAY",
		2: "CONCOX",
		3: "HOWEN",
		4: "AQUILA",
		5: "INTELLITRAC",
		6: "QUECLINK_GV200",
		7: "QUECLINK_GT500",
	}
	DeviceType_value = map[string]int32{
		"TELTONIKA":      0,
		"WANWAY":         1,
		"CONCOX":         2,
		"HOWEN":          3,
		"AQUILA":         4,
		"INTELLITRAC":    5,
		"QUECLINK_GV200": 6,
		"QUECLINK_GT500": 7,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_common_types_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{0}
}

type DeviceProtocolType int32

const (
	DeviceProtocolType_FM1200        DeviceProtocolType = 0
	DeviceProtocolType_GT06          DeviceProtocolType = 1
	DeviceProtocolType_TR06          DeviceProtocolType = 2
	DeviceProtocolType_HOWENWS       DeviceProtocolType = 3
	DeviceProtocolType_OBDII2G       DeviceProtocolType = 4
	DeviceProtocolType_INTELLITRAC_A DeviceProtocolType = 5
	DeviceProtocolType_QUECLINK      DeviceProtocolType = 6
)

// Enum value maps for DeviceProtocolType.
var (
	DeviceProtocolType_name = map[int32]string{
		0: "FM1200",
		1: "GT06",
		2: "TR06",
		3: "HOWENWS",
		4: "OBDII2G",
		5: "INTELLITRAC_A",
		6: "QUECLINK",
	}
	DeviceProtocolType_value = map[string]int32{
		"FM1200":        0,
		"GT06":          1,
		"TR06":          2,
		"HOWENWS":       3,
		"OBDII2G":       4,
		"INTELLITRAC_A": 5,
		"QUECLINK":      6,
	}
)

func (x DeviceProtocolType) Enum() *DeviceProtocolType {
	p := new(DeviceProtocolType)
	*p = x
	return p
}

func (x DeviceProtocolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceProtocolType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_proto_enumTypes[1].Descriptor()
}

func (DeviceProtocolType) Type() protoreflect.EnumType {
	return &file_common_types_proto_enumTypes[1]
}

func (x DeviceProtocolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceProtocolType.Descriptor instead.
func (DeviceProtocolType) EnumDescriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{1}
}

type DeviceStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Imei                 string                 `protobuf:"bytes,1,opt,name=imei,proto3" json:"imei,omitempty"`
	DeviceType           DeviceType             `protobuf:"varint,2,opt,name=device_type,json=deviceType,proto3,enum=types.DeviceType" json:"device_type,omitempty"`
	Timestamp            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MessageType          string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Position             *GPSPosition           `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	VehicleStatus        *VehicleStatus         `protobuf:"bytes,6,opt,name=vehicle_status,json=vehicleStatus,proto3" json:"vehicle_status,omitempty"`
	BatteryLevel         int32                  `protobuf:"varint,7,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	Temperature          float32                `protobuf:"fixed32,8,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Odometer             int32                  `protobuf:"varint,9,opt,name=odometer,proto3" json:"odometer,omitempty"`
	FuelLtr              int32                  `protobuf:"varint,10,opt,name=fuel_ltr,json=fuelLtr,proto3" json:"fuel_ltr,omitempty"`
	FuelPct              int32                  `protobuf:"varint,11,opt,name=fuel_pct,json=fuelPct,proto3" json:"fuel_pct,omitempty"`
	FuelGps              int32                  `protobuf:"varint,12,opt,name=fuel_gps,json=fuelGps,proto3" json:"fuel_gps,omitempty"`
	IdentificationId     string                 `protobuf:"bytes,13,opt,name=identification_id,json=identificationId,proto3" json:"identification_id,omitempty"`
	Vin                  string                 `protobuf:"bytes,14,opt,name=vin,proto3" json:"vin,omitempty"`
	Rpm                  int32                  `protobuf:"varint,15,opt,name=rpm,proto3" json:"rpm,omitempty"`
	CoolantTemperature   float32                `protobuf:"fixed32,16,opt,name=coolant_temperature,json=coolantTemperature,proto3" json:"coolant_temperature,omitempty"`
	EngineLoad           float32                `protobuf:"fixed32,17,opt,name=engine_load,json=engineLoad,proto3" json:"engine_load,omitempty"`
	IntakeAirTemp        float32                `protobuf:"fixed32,18,opt,name=intake_air_temp,json=intakeAirTemp,proto3" json:"intake_air_temp,omitempty"`
	RunTime              uint32                 `protobuf:"varint,19,opt,name=run_time,json=runTime,proto3" json:"run_time,omitempty"`
	DistanceMilOn        uint32                 `protobuf:"varint,20,opt,name=distance_mil_on,json=distanceMilOn,proto3" json:"distance_mil_on,omitempty"`
	FuelLevelInput       float32                `protobuf:"fixed32,21,opt,name=fuel_level_input,json=fuelLevelInput,proto3" json:"fuel_level_input,omitempty"`
	MafAirFlow           float32                `protobuf:"fixed32,22,opt,name=maf_air_flow,json=mafAirFlow,proto3" json:"maf_air_flow,omitempty"`
	FuelRailPressure     float32                `protobuf:"fixed32,23,opt,name=fuel_rail_pressure,json=fuelRailPressure,proto3" json:"fuel_rail_pressure,omitempty"`
	WarmupsSinceClear    uint32                 `protobuf:"varint,24,opt,name=warmups_since_clear,json=warmupsSinceClear,proto3" json:"warmups_since_clear,omitempty"`
	DistanceSinceClear   uint32                 `protobuf:"varint,25,opt,name=distance_since_clear,json=distanceSinceClear,proto3" json:"distance_since_clear,omitempty"`
	BarometricPressure   int32                  `protobuf:"varint,26,opt,name=barometric_pressure,json=barometricPressure,proto3" json:"barometric_pressure,omitempty"`
	ControlModuleVoltage float32                `protobuf:"fixed32,27,opt,name=control_module_voltage,json=controlModuleVoltage,proto3" json:"control_module_voltage,omitempty"`
	AbsoluteLoadValue    float32                `protobuf:"fixed32,28,opt,name=absolute_load_value,json=absoluteLoadValue,proto3" json:"absolute_load_value,omitempty"`
	EngineOilTemp        float32                `protobuf:"fixed32,29,opt,name=engine_oil_temp,json=engineOilTemp,proto3" json:"engine_oil_temp,omitempty"`
	GsmNetwork           int32                  `protobuf:"varint,30,opt,name=gsm_network,json=gsmNetwork,proto3" json:"gsm_network,omitempty"`
	BatteryChargeLevel   int32                  `protobuf:"varint,31,opt,name=battery_charge_level,json=batteryChargeLevel,proto3" json:"battery_charge_level,omitempty"`
	RemainingDistance    int32                  `protobuf:"varint,32,opt,name=remaining_distance,json=remainingDistance,proto3" json:"remaining_distance,omitempty"`
	BatteryStateOfHealth int32                  `protobuf:"varint,33,opt,name=battery_state_of_health,json=batteryStateOfHealth,proto3" json:"battery_state_of_health,omitempty"`
	BatteryTemp          int32                  `protobuf:"varint,34,opt,name=battery_temp,json=batteryTemp,proto3" json:"battery_temp,omitempty"`
	// Types that are valid to be assigned to RawData:
	//
	//	*DeviceStatus_WanwayPacket
	//	*DeviceStatus_TeltonikaPacket
	//	*DeviceStatus_ConcoxPacket
	//	*DeviceStatus_HowenPacket
	//	*DeviceStatus_AquilaPacket
	//	*DeviceStatus_IntellitracPacket
	//	*DeviceStatus_QueclinkPacket
	RawData       isDeviceStatus_RawData `protobuf_oneof:"raw_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatus) Reset() {
	*x = DeviceStatus{}
	mi := &file_common_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatus) ProtoMessage() {}

func (x *DeviceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatus.ProtoReflect.Descriptor instead.
func (*DeviceStatus) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceStatus) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *DeviceStatus) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_TELTONIKA
}

func (x *DeviceStatus) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DeviceStatus) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *DeviceStatus) GetPosition() *GPSPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *DeviceStatus) GetVehicleStatus() *VehicleStatus {
	if x != nil {
		return x.VehicleStatus
	}
	return nil
}

func (x *DeviceStatus) GetBatteryLevel() int32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *DeviceStatus) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *DeviceStatus) GetOdometer() int32 {
	if x != nil {
		return x.Odometer
	}
	return 0
}

func (x *DeviceStatus) GetFuelLtr() int32 {
	if x != nil {
		return x.FuelLtr
	}
	return 0
}

func (x *DeviceStatus) GetFuelPct() int32 {
	if x != nil {
		return x.FuelPct
	}
	return 0
}

func (x *DeviceStatus) GetFuelGps() int32 {
	if x != nil {
		return x.FuelGps
	}
	return 0
}

func (x *DeviceStatus) GetIdentificationId() string {
	if x != nil {
		return x.IdentificationId
	}
	return ""
}

func (x *DeviceStatus) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *DeviceStatus) GetRpm() int32 {
	if x != nil {
		return x.Rpm
	}
	return 0
}

func (x *DeviceStatus) GetCoolantTemperature() float32 {
	if x != nil {
		return x.CoolantTemperature
	}
	return 0
}

func (x *DeviceStatus) GetEngineLoad() float32 {
	if x != nil {
		return x.EngineLoad
	}
	return 0
}

func (x *DeviceStatus) GetIntakeAirTemp() float32 {
	if x != nil {
		return x.IntakeAirTemp
	}
	return 0
}

func (x *DeviceStatus) GetRunTime() uint32 {
	if x != nil {
		return x.RunTime
	}
	return 0
}

func (x *DeviceStatus) GetDistanceMilOn() uint32 {
	if x != nil {
		return x.DistanceMilOn
	}
	return 0
}

func (x *DeviceStatus) GetFuelLevelInput() float32 {
	if x != nil {
		return x.FuelLevelInput
	}
	return 0
}

func (x *DeviceStatus) GetMafAirFlow() float32 {
	if x != nil {
		return x.MafAirFlow
	}
	return 0
}

func (x *DeviceStatus) GetFuelRailPressure() float32 {
	if x != nil {
		return x.FuelRailPressure
	}
	return 0
}

func (x *DeviceStatus) GetWarmupsSinceClear() uint32 {
	if x != nil {
		return x.WarmupsSinceClear
	}
	return 0
}

func (x *DeviceStatus) GetDistanceSinceClear() uint32 {
	if x != nil {
		return x.DistanceSinceClear
	}
	return 0
}

func (x *DeviceStatus) GetBarometricPressure() int32 {
	if x != nil {
		return x.BarometricPressure
	}
	return 0
}

func (x *DeviceStatus) GetControlModuleVoltage() float32 {
	if x != nil {
		return x.ControlModuleVoltage
	}
	return 0
}

func (x *DeviceStatus) GetAbsoluteLoadValue() float32 {
	if x != nil {
		return x.AbsoluteLoadValue
	}
	return 0
}

func (x *DeviceStatus) GetEngineOilTemp() float32 {
	if x != nil {
		return x.EngineOilTemp
	}
	return 0
}

func (x *DeviceStatus) GetGsmNetwork() int32 {
	if x != nil {
		return x.GsmNetwork
	}
	return 0
}

func (x *DeviceStatus) GetBatteryChargeLevel() int32 {
	if x != nil {
		return x.BatteryChargeLevel
	}
	return 0
}

func (x *DeviceStatus) GetRemainingDistance() int32 {
	if x != nil {
		return x.RemainingDistance
	}
	return 0
}

func (x *DeviceStatus) GetBatteryStateOfHealth() int32 {
	if x != nil {
		return x.BatteryStateOfHealth
	}
	return 0
}

func (x *DeviceStatus) GetBatteryTemp() int32 {
	if x != nil {
		return x.BatteryTemp
	}
	return 0
}

func (x *DeviceStatus) GetRawData() isDeviceStatus_RawData {
	if x != nil {
		return x.RawData
	}
	return nil
}

func (x *DeviceStatus) GetWanwayPacket() *WanwayPacket {
	if x != nil {
		if x, ok := x.RawData.(*DeviceStatus_WanwayPacket); ok {
			return x.WanwayPacket
		}
	}
	return nil
}

func (x *DeviceStatus) GetTeltonikaPacket() *TeltonikaPacket {
	if x != nil {
		if x, ok := x.RawData.(*DeviceStatus_TeltonikaPacket); ok {
			return x.TeltonikaPacket
		}
	}
	return nil
}

func (x *DeviceStatus) GetConcoxPacket() *ConcoxPacket {
	if x != nil {
		if x, ok := x.RawData.(*DeviceStatus_ConcoxPacket); ok {
			return x.ConcoxPacket
		}
	}
	return nil
}

func (x *DeviceStatus) GetHowenPacket() *HowenPacket {
	if x != nil {
		if x, ok := x.RawData.(*DeviceStatus_HowenPacket); ok {
			return x.HowenPacket
		}
	}
	return nil
}

func (x *DeviceStatus) GetAquilaPacket() *AquilaPacket {
	if x != nil {
		if x, ok := x.RawData.(*DeviceStatus_AquilaPacket); ok {
			return x.AquilaPacket
		}
	}
	return nil
}

func (x *DeviceStatus) GetIntellitracPacket() *IntellitracPacket {
	if x != nil {
		if x, ok := x.RawData.(*DeviceStatus_IntellitracPacket); ok {
			return x.IntellitracPacket
		}
	}
	return nil
}

func (x *DeviceStatus) GetQueclinkPacket() *QueclinkPacket {
	if x != nil {
		if x, ok := x.RawData.(*DeviceStatus_QueclinkPacket); ok {
			return x.QueclinkPacket
		}
	}
	return nil
}

type isDeviceStatus_RawData interface {
	isDeviceStatus_RawData()
}

type DeviceStatus_WanwayPacket struct {
	WanwayPacket *WanwayPacket `protobuf:"bytes,35,opt,name=wanway_packet,json=wanwayPacket,proto3,oneof"`
}

type DeviceStatus_TeltonikaPacket struct {
	TeltonikaPacket *TeltonikaPacket `protobuf:"bytes,36,opt,name=teltonika_packet,json=teltonikaPacket,proto3,oneof"`
}

type DeviceStatus_ConcoxPacket struct {
	ConcoxPacket *ConcoxPacket `protobuf:"bytes,37,opt,name=concox_packet,json=concoxPacket,proto3,oneof"`
}

type DeviceStatus_HowenPacket struct {
	HowenPacket *HowenPacket `protobuf:"bytes,38,opt,name=howen_packet,json=howenPacket,proto3,oneof"`
}

type DeviceStatus_AquilaPacket struct {
	AquilaPacket *AquilaPacket `protobuf:"bytes,39,opt,name=aquila_packet,json=aquilaPacket,proto3,oneof"`
}

type DeviceStatus_IntellitracPacket struct {
	IntellitracPacket *IntellitracPacket `protobuf:"bytes,40,opt,name=intellitrac_packet,json=intellitracPacket,proto3,oneof"`
}

type DeviceStatus_QueclinkPacket struct {
	QueclinkPacket *QueclinkPacket `protobuf:"bytes,41,opt,name=queclink_packet,json=queclinkPacket,proto3,oneof"`
}

func (*DeviceStatus_WanwayPacket) isDeviceStatus_RawData() {}

func (*DeviceStatus_TeltonikaPacket) isDeviceStatus_RawData() {}

func (*DeviceStatus_ConcoxPacket) isDeviceStatus_RawData() {}

func (*DeviceStatus_HowenPacket) isDeviceStatus_RawData() {}

func (*DeviceStatus_AquilaPacket) isDeviceStatus_RawData() {}

func (*DeviceStatus_IntellitracPacket) isDeviceStatus_RawData() {}

func (*DeviceStatus_QueclinkPacket) isDeviceStatus_RawData() {}

type GPSPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float32                `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude      float32                `protobuf:"fixed32,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Speed         *float32               `protobuf:"fixed32,4,opt,name=speed,proto3,oneof" json:"speed,omitempty"`
	Course        float32                `protobuf:"fixed32,5,opt,name=course,proto3" json:"course,omitempty"`
	Satellites    int32                  `protobuf:"varint,6,opt,name=satellites,proto3" json:"satellites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPSPosition) Reset() {
	*x = GPSPosition{}
	mi := &file_common_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPSPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPSPosition) ProtoMessage() {}

func (x *GPSPosition) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPSPosition.ProtoReflect.Descriptor instead.
func (*GPSPosition) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{1}
}

func (x *GPSPosition) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GPSPosition) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GPSPosition) GetAltitude() float32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *GPSPosition) GetSpeed() float32 {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return 0
}

func (x *GPSPosition) GetCourse() float32 {
	if x != nil {
		return x.Course
	}
	return 0
}

func (x *GPSPosition) GetSatellites() int32 {
	if x != nil {
		return x.Satellites
	}
	return 0
}

type VehicleStatus struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Ignition               *bool                  `protobuf:"varint,1,opt,name=ignition,proto3,oneof" json:"ignition,omitempty"`
	OverSpeeding           bool                   `protobuf:"varint,2,opt,name=over_speeding,json=overSpeeding,proto3" json:"over_speeding,omitempty"`
	RashDriving            bool                   `protobuf:"varint,3,opt,name=rash_driving,json=rashDriving,proto3" json:"rash_driving,omitempty"`
	CrashDetection         bool                   `protobuf:"varint,4,opt,name=crash_detection,json=crashDetection,proto3" json:"crash_detection,omitempty"`
	UnplugBattery          bool                   `protobuf:"varint,5,opt,name=unplug_battery,json=unplugBattery,proto3" json:"unplug_battery,omitempty"`
	Towing                 bool                   `protobuf:"varint,6,opt,name=towing,proto3" json:"towing,omitempty"`
	AutoGeofence           bool                   `protobuf:"varint,7,opt,name=auto_geofence,json=autoGeofence,proto3" json:"auto_geofence,omitempty"`
	ExcessiveIdling        bool                   `protobuf:"varint,8,opt,name=excessive_idling,json=excessiveIdling,proto3" json:"excessive_idling,omitempty"`
	RouteDeviation         bool                   `protobuf:"varint,9,opt,name=route_deviation,json=routeDeviation,proto3" json:"route_deviation,omitempty"`
	VibrationDetected      bool                   `protobuf:"varint,10,opt,name=vibration_detected,json=vibrationDetected,proto3" json:"vibration_detected,omitempty"`                  // Vibration sensor triggered
	DistanceBetweenObjects bool                   `protobuf:"varint,11,opt,name=distance_between_objects,json=distanceBetweenObjects,proto3" json:"distance_between_objects,omitempty"` // Objects too close
	DriverAbsence          bool                   `protobuf:"varint,12,opt,name=driver_absence,json=driverAbsence,proto3" json:"driver_absence,omitempty"`                              // No driver detected
	DriverChange           bool                   `protobuf:"varint,13,opt,name=driver_change,json=driverChange,proto3" json:"driver_change,omitempty"`                                 // Driver change detected
	DriverDistraction      bool                   `protobuf:"varint,14,opt,name=driver_distraction,json=driverDistraction,proto3" json:"driver_distraction,omitempty"`                  // Driver distraction event
	EntringGeofence        bool                   `protobuf:"varint,15,opt,name=entring_geofence,json=entringGeofence,proto3" json:"entring_geofence,omitempty"`                        // Enter or exit geofence
	ExcessiveDriving       bool                   `protobuf:"varint,16,opt,name=excessive_driving,json=excessiveDriving,proto3" json:"excessive_driving,omitempty"`                     // Excessive driving hours
	ExcessiveParking       bool                   `protobuf:"varint,17,opt,name=excessive_parking,json=excessiveParking,proto3" json:"excessive_parking,omitempty"`                     // Excessive parking detected
	FatigueDriving         bool                   `protobuf:"varint,18,opt,name=fatigue_driving,json=fatigueDriving,proto3" json:"fatigue_driving,omitempty"`                           // Fatigue driving
	FuelRefuel             bool                   `protobuf:"varint,19,opt,name=fuel_refuel,json=fuelRefuel,proto3" json:"fuel_refuel,omitempty"`                                       // Fuel theft or refuel
	TrackerOffline         bool                   `protobuf:"varint,20,opt,name=tracker_offline,json=trackerOffline,proto3" json:"tracker_offline,omitempty"`                           // Tracker switched off or lost
	InputsTriggering       bool                   `protobuf:"varint,21,opt,name=inputs_triggering,json=inputsTriggering,proto3" json:"inputs_triggering,omitempty"`                     // Inputs triggering detected
	OutputsTriggering      bool                   `protobuf:"varint,22,opt,name=outputs_triggering,json=outputsTriggering,proto3" json:"outputs_triggering,omitempty"`                  // Outputs triggering detected
	ParameterInRange       bool                   `protobuf:"varint,23,opt,name=parameter_in_range,json=parameterInRange,proto3" json:"parameter_in_range,omitempty"`                   // Parameter within range
	ParkingState           bool                   `protobuf:"varint,24,opt,name=parking_state,json=parkingState,proto3" json:"parking_state,omitempty"`                                 // Parking state detection
	SosButtonPressed       bool                   `protobuf:"varint,25,opt,name=sos_button_pressed,json=sosButtonPressed,proto3" json:"sos_button_pressed,omitempty"`                   // SOS button event
	StateFieldValueChange  bool                   `protobuf:"varint,27,opt,name=state_field_value_change,json=stateFieldValueChange,proto3" json:"state_field_value_change,omitempty"`  // State field value updated
	TaskStatusChange       bool                   `protobuf:"varint,28,opt,name=task_status_change,json=taskStatusChange,proto3" json:"task_status_change,omitempty"`                   // Task status changed
	ExitingGeofence        bool                   `protobuf:"varint,29,opt,name=exiting_geofence,json=exitingGeofence,proto3" json:"exiting_geofence,omitempty"`
	FuelTheft              bool                   `protobuf:"varint,30,opt,name=fuel_theft,json=fuelTheft,proto3" json:"fuel_theft,omitempty"`
	HarshAcceleration      bool                   `protobuf:"varint,31,opt,name=harsh_acceleration,json=harshAcceleration,proto3" json:"harsh_acceleration,omitempty"`
	HarshBraking           bool                   `protobuf:"varint,32,opt,name=harsh_braking,json=harshBraking,proto3" json:"harsh_braking,omitempty"`
	HarshCornering         bool                   `protobuf:"varint,33,opt,name=harsh_cornering,json=harshCornering,proto3" json:"harsh_cornering,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *VehicleStatus) Reset() {
	*x = VehicleStatus{}
	mi := &file_common_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleStatus) ProtoMessage() {}

func (x *VehicleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleStatus.ProtoReflect.Descriptor instead.
func (*VehicleStatus) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{2}
}

func (x *VehicleStatus) GetIgnition() bool {
	if x != nil && x.Ignition != nil {
		return *x.Ignition
	}
	return false
}

func (x *VehicleStatus) GetOverSpeeding() bool {
	if x != nil {
		return x.OverSpeeding
	}
	return false
}

func (x *VehicleStatus) GetRashDriving() bool {
	if x != nil {
		return x.RashDriving
	}
	return false
}

func (x *VehicleStatus) GetCrashDetection() bool {
	if x != nil {
		return x.CrashDetection
	}
	return false
}

func (x *VehicleStatus) GetUnplugBattery() bool {
	if x != nil {
		return x.UnplugBattery
	}
	return false
}

func (x *VehicleStatus) GetTowing() bool {
	if x != nil {
		return x.Towing
	}
	return false
}

func (x *VehicleStatus) GetAutoGeofence() bool {
	if x != nil {
		return x.AutoGeofence
	}
	return false
}

func (x *VehicleStatus) GetExcessiveIdling() bool {
	if x != nil {
		return x.ExcessiveIdling
	}
	return false
}

func (x *VehicleStatus) GetRouteDeviation() bool {
	if x != nil {
		return x.RouteDeviation
	}
	return false
}

func (x *VehicleStatus) GetVibrationDetected() bool {
	if x != nil {
		return x.VibrationDetected
	}
	return false
}

func (x *VehicleStatus) GetDistanceBetweenObjects() bool {
	if x != nil {
		return x.DistanceBetweenObjects
	}
	return false
}

func (x *VehicleStatus) GetDriverAbsence() bool {
	if x != nil {
		return x.DriverAbsence
	}
	return false
}

func (x *VehicleStatus) GetDriverChange() bool {
	if x != nil {
		return x.DriverChange
	}
	return false
}

func (x *VehicleStatus) GetDriverDistraction() bool {
	if x != nil {
		return x.DriverDistraction
	}
	return false
}

func (x *VehicleStatus) GetEntringGeofence() bool {
	if x != nil {
		return x.EntringGeofence
	}
	return false
}

func (x *VehicleStatus) GetExcessiveDriving() bool {
	if x != nil {
		return x.ExcessiveDriving
	}
	return false
}

func (x *VehicleStatus) GetExcessiveParking() bool {
	if x != nil {
		return x.ExcessiveParking
	}
	return false
}

func (x *VehicleStatus) GetFatigueDriving() bool {
	if x != nil {
		return x.FatigueDriving
	}
	return false
}

func (x *VehicleStatus) GetFuelRefuel() bool {
	if x != nil {
		return x.FuelRefuel
	}
	return false
}

func (x *VehicleStatus) GetTrackerOffline() bool {
	if x != nil {
		return x.TrackerOffline
	}
	return false
}

func (x *VehicleStatus) GetInputsTriggering() bool {
	if x != nil {
		return x.InputsTriggering
	}
	return false
}

func (x *VehicleStatus) GetOutputsTriggering() bool {
	if x != nil {
		return x.OutputsTriggering
	}
	return false
}

func (x *VehicleStatus) GetParameterInRange() bool {
	if x != nil {
		return x.ParameterInRange
	}
	return false
}

func (x *VehicleStatus) GetParkingState() bool {
	if x != nil {
		return x.ParkingState
	}
	return false
}

func (x *VehicleStatus) GetSosButtonPressed() bool {
	if x != nil {
		return x.SosButtonPressed
	}
	return false
}

func (x *VehicleStatus) GetStateFieldValueChange() bool {
	if x != nil {
		return x.StateFieldValueChange
	}
	return false
}

func (x *VehicleStatus) GetTaskStatusChange() bool {
	if x != nil {
		return x.TaskStatusChange
	}
	return false
}

func (x *VehicleStatus) GetExitingGeofence() bool {
	if x != nil {
		return x.ExitingGeofence
	}
	return false
}

func (x *VehicleStatus) GetFuelTheft() bool {
	if x != nil {
		return x.FuelTheft
	}
	return false
}

func (x *VehicleStatus) GetHarshAcceleration() bool {
	if x != nil {
		return x.HarshAcceleration
	}
	return false
}

func (x *VehicleStatus) GetHarshBraking() bool {
	if x != nil {
		return x.HarshBraking
	}
	return false
}

func (x *VehicleStatus) GetHarshCornering() bool {
	if x != nil {
		return x.HarshCornering
	}
	return false
}

type WanwayPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawData       []byte                 `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WanwayPacket) Reset() {
	*x = WanwayPacket{}
	mi := &file_common_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WanwayPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WanwayPacket) ProtoMessage() {}

func (x *WanwayPacket) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WanwayPacket.ProtoReflect.Descriptor instead.
func (*WanwayPacket) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{3}
}

func (x *WanwayPacket) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type TeltonikaPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawData       []byte                 `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeltonikaPacket) Reset() {
	*x = TeltonikaPacket{}
	mi := &file_common_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeltonikaPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeltonikaPacket) ProtoMessage() {}

func (x *TeltonikaPacket) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeltonikaPacket.ProtoReflect.Descriptor instead.
func (*TeltonikaPacket) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{4}
}

func (x *TeltonikaPacket) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type ConcoxPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawData       []byte                 `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcoxPacket) Reset() {
	*x = ConcoxPacket{}
	mi := &file_common_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcoxPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcoxPacket) ProtoMessage() {}

func (x *ConcoxPacket) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcoxPacket.ProtoReflect.Descriptor instead.
func (*ConcoxPacket) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{5}
}

func (x *ConcoxPacket) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type HowenPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawData       []byte                 `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HowenPacket) Reset() {
	*x = HowenPacket{}
	mi := &file_common_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HowenPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HowenPacket) ProtoMessage() {}

func (x *HowenPacket) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HowenPacket.ProtoReflect.Descriptor instead.
func (*HowenPacket) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{6}
}

func (x *HowenPacket) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type AquilaPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawData       []byte                 `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AquilaPacket) Reset() {
	*x = AquilaPacket{}
	mi := &file_common_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AquilaPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AquilaPacket) ProtoMessage() {}

func (x *AquilaPacket) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AquilaPacket.ProtoReflect.Descriptor instead.
func (*AquilaPacket) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{7}
}

func (x *AquilaPacket) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type IntellitracPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawData       []byte                 `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntellitracPacket) Reset() {
	*x = IntellitracPacket{}
	mi := &file_common_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntellitracPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntellitracPacket) ProtoMessage() {}

func (x *IntellitracPacket) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntellitracPacket.ProtoReflect.Descriptor instead.
func (*IntellitracPacket) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{8}
}

func (x *IntellitracPacket) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type QueclinkPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawData       []byte                 `protobuf:"bytes,1,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueclinkPacket) Reset() {
	*x = QueclinkPacket{}
	mi := &file_common_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueclinkPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueclinkPacket) ProtoMessage() {}

func (x *QueclinkPacket) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueclinkPacket.ProtoReflect.Descriptor instead.
func (*QueclinkPacket) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{9}
}

func (x *QueclinkPacket) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type DeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Imei          string                 `protobuf:"bytes,1,opt,name=imei,proto3" json:"imei,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceResponse) Reset() {
	*x = DeviceResponse{}
	mi := &file_common_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceResponse) ProtoMessage() {}

func (x *DeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceResponse.ProtoReflect.Descriptor instead.
func (*DeviceResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{10}
}

func (x *DeviceResponse) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *DeviceResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type FetchDeviceModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Imei          string                 `protobuf:"bytes,1,opt,name=imei,proto3" json:"imei,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchDeviceModelRequest) Reset() {
	*x = FetchDeviceModelRequest{}
	mi := &file_common_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchDeviceModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDeviceModelRequest) ProtoMessage() {}

func (x *FetchDeviceModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDeviceModelRequest.ProtoReflect.Descriptor instead.
func (*FetchDeviceModelRequest) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{11}
}

func (x *FetchDeviceModelRequest) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

type FetchDeviceModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchDeviceModelResponse) Reset() {
	*x = FetchDeviceModelResponse{}
	mi := &file_common_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchDeviceModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchDeviceModelResponse) ProtoMessage() {}

func (x *FetchDeviceModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchDeviceModelResponse.ProtoReflect.Descriptor instead.
func (*FetchDeviceModelResponse) Descriptor() ([]byte, []int) {
	return file_common_types_proto_rawDescGZIP(), []int{12}
}

func (x *FetchDeviceModelResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_common_types_proto protoreflect.FileDescriptor

const file_common_types_proto_rawDesc = "" +
	"\n" +
	"\x12common-types.proto\x12\x05types\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa4\x0e\n" +
	"\fDeviceStatus\x12\x12\n" +
	"\x04imei\x18\x01 \x01(\tR\x04imei\x122\n" +
	"\vdevice_type\x18\x02 \x01(\x0e2\x11.types.DeviceTypeR\n" +
	"deviceType\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\x12.\n" +
	"\bposition\x18\x05 \x01(\v2\x12.types.GPSPositionR\bposition\x12;\n" +
	"\x0evehicle_status\x18\x06 \x01(\v2\x14.types.VehicleStatusR\rvehicleStatus\x12#\n" +
	"\rbattery_level\x18\a \x01(\x05R\fbatteryLevel\x12 \n" +
	"\vtemperature\x18\b \x01(\x02R\vtemperature\x12\x1a\n" +
	"\bodometer\x18\t \x01(\x05R\bodometer\x12\x19\n" +
	"\bfuel_ltr\x18\n" +
	" \x01(\x05R\afuelLtr\x12\x19\n" +
	"\bfuel_pct\x18\v \x01(\x05R\afuelPct\x12\x19\n" +
	"\bfuel_gps\x18\f \x01(\x05R\afuelGps\x12+\n" +
	"\x11identification_id\x18\r \x01(\tR\x10identificationId\x12\x10\n" +
	"\x03vin\x18\x0e \x01(\tR\x03vin\x12\x10\n" +
	"\x03rpm\x18\x0f \x01(\x05R\x03rpm\x12/\n" +
	"\x13coolant_temperature\x18\x10 \x01(\x02R\x12coolantTemperature\x12\x1f\n" +
	"\vengine_load\x18\x11 \x01(\x02R\n" +
	"engineLoad\x12&\n" +
	"\x0fintake_air_temp\x18\x12 \x01(\x02R\rintakeAirTemp\x12\x19\n" +
	"\brun_time\x18\x13 \x01(\rR\arunTime\x12&\n" +
	"\x0fdistance_mil_on\x18\x14 \x01(\rR\rdistanceMilOn\x12(\n" +
	"\x10fuel_level_input\x18\x15 \x01(\x02R\x0efuelLevelInput\x12 \n" +
	"\fmaf_air_flow\x18\x16 \x01(\x02R\n" +
	"mafAirFlow\x12,\n" +
	"\x12fuel_rail_pressure\x18\x17 \x01(\x02R\x10fuelRailPressure\x12.\n" +
	"\x13warmups_since_clear\x18\x18 \x01(\rR\x11warmupsSinceClear\x120\n" +
	"\x14distance_since_clear\x18\x19 \x01(\rR\x12distanceSinceClear\x12/\n" +
	"\x13barometric_pressure\x18\x1a \x01(\x05R\x12barometricPressure\x124\n" +
	"\x16control_module_voltage\x18\x1b \x01(\x02R\x14controlModuleVoltage\x12.\n" +
	"\x13absolute_load_value\x18\x1c \x01(\x02R\x11absoluteLoadValue\x12&\n" +
	"\x0fengine_oil_temp\x18\x1d \x01(\x02R\rengineOilTemp\x12\x1f\n" +
	"\vgsm_network\x18\x1e \x01(\x05R\n" +
	"gsmNetwork\x120\n" +
	"\x14battery_charge_level\x18\x1f \x01(\x05R\x12batteryChargeLevel\x12-\n" +
	"\x12remaining_distance\x18  \x01(\x05R\x11remainingDistance\x125\n" +
	"\x17battery_state_of_health\x18! \x01(\x05R\x14batteryStateOfHealth\x12!\n" +
	"\fbattery_temp\x18\" \x01(\x05R\vbatteryTemp\x12:\n" +
	"\rwanway_packet\x18# \x01(\v2\x13.types.WanwayPacketH\x00R\fwanwayPacket\x12C\n" +
	"\x10teltonika_packet\x18$ \x01(\v2\x16.types.TeltonikaPacketH\x00R\x0fteltonikaPacket\x12:\n" +
	"\rconcox_packet\x18% \x01(\v2\x13.types.ConcoxPacketH\x00R\fconcoxPacket\x127\n" +
	"\fhowen_packet\x18& \x01(\v2\x12.types.HowenPacketH\x00R\vhowenPacket\x12:\n" +
	"\raquila_packet\x18' \x01(\v2\x13.types.AquilaPacketH\x00R\faquilaPacket\x12I\n" +
	"\x12intellitrac_packet\x18( \x01(\v2\x18.types.IntellitracPacketH\x00R\x11intellitracPacket\x12@\n" +
	"\x0fqueclink_packet\x18) \x01(\v2\x15.types.QueclinkPacketH\x00R\x0equeclinkPacketB\n" +
	"\n" +
	"\braw_data\"\xc0\x01\n" +
	"\vGPSPosition\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x02R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x03 \x01(\x02R\baltitude\x12\x19\n" +
	"\x05speed\x18\x04 \x01(\x02H\x00R\x05speed\x88\x01\x01\x12\x16\n" +
	"\x06course\x18\x05 \x01(\x02R\x06course\x12\x1e\n" +
	"\n" +
	"satellites\x18\x06 \x01(\x05R\n" +
	"satellitesB\b\n" +
	"\x06_speed\"\xcd\n" +
	"\n" +
	"\rVehicleStatus\x12\x1f\n" +
	"\bignition\x18\x01 \x01(\bH\x00R\bignition\x88\x01\x01\x12#\n" +
	"\rover_speeding\x18\x02 \x01(\bR\foverSpeeding\x12!\n" +
	"\frash_driving\x18\x03 \x01(\bR\vrashDriving\x12'\n" +
	"\x0fcrash_detection\x18\x04 \x01(\bR\x0ecrashDetection\x12%\n" +
	"\x0eunplug_battery\x18\x05 \x01(\bR\runplugBattery\x12\x16\n" +
	"\x06towing\x18\x06 \x01(\bR\x06towing\x12#\n" +
	"\rauto_geofence\x18\a \x01(\bR\fautoGeofence\x12)\n" +
	"\x10excessive_idling\x18\b \x01(\bR\x0fexcessiveIdling\x12'\n" +
	"\x0froute_deviation\x18\t \x01(\bR\x0erouteDeviation\x12-\n" +
	"\x12vibration_detected\x18\n" +
	" \x01(\bR\x11vibrationDetected\x128\n" +
	"\x18distance_between_objects\x18\v \x01(\bR\x16distanceBetweenObjects\x12%\n" +
	"\x0edriver_absence\x18\f \x01(\bR\rdriverAbsence\x12#\n" +
	"\rdriver_change\x18\r \x01(\bR\fdriverChange\x12-\n" +
	"\x12driver_distraction\x18\x0e \x01(\bR\x11driverDistraction\x12)\n" +
	"\x10entring_geofence\x18\x0f \x01(\bR\x0fentringGeofence\x12+\n" +
	"\x11excessive_driving\x18\x10 \x01(\bR\x10excessiveDriving\x12+\n" +
	"\x11excessive_parking\x18\x11 \x01(\bR\x10excessiveParking\x12'\n" +
	"\x0ffatigue_driving\x18\x12 \x01(\bR\x0efatigueDriving\x12\x1f\n" +
	"\vfuel_refuel\x18\x13 \x01(\bR\n" +
	"fuelRefuel\x12'\n" +
	"\x0ftracker_offline\x18\x14 \x01(\bR\x0etrackerOffline\x12+\n" +
	"\x11inputs_triggering\x18\x15 \x01(\bR\x10inputsTriggering\x12-\n" +
	"\x12outputs_triggering\x18\x16 \x01(\bR\x11outputsTriggering\x12,\n" +
	"\x12parameter_in_range\x18\x17 \x01(\bR\x10parameterInRange\x12#\n" +
	"\rparking_state\x18\x18 \x01(\bR\fparkingState\x12,\n" +
	"\x12sos_button_pressed\x18\x19 \x01(\bR\x10sosButtonPressed\x127\n" +
	"\x18state_field_value_change\x18\x1b \x01(\bR\x15stateFieldValueChange\x12,\n" +
	"\x12task_status_change\x18\x1c \x01(\bR\x10taskStatusChange\x12)\n" +
	"\x10exiting_geofence\x18\x1d \x01(\bR\x0fexitingGeofence\x12\x1d\n" +
	"\n" +
	"fuel_theft\x18\x1e \x01(\bR\tfuelTheft\x12-\n" +
	"\x12harsh_acceleration\x18\x1f \x01(\bR\x11harshAcceleration\x12#\n" +
	"\rharsh_braking\x18  \x01(\bR\fharshBraking\x12'\n" +
	"\x0fharsh_cornering\x18! \x01(\bR\x0eharshCorneringB\v\n" +
	"\t_ignition\")\n" +
	"\fWanwayPacket\x12\x19\n" +
	"\braw_data\x18\x01 \x01(\fR\arawData\",\n" +
	"\x0fTeltonikaPacket\x12\x19\n" +
	"\braw_data\x18\x01 \x01(\fR\arawData\")\n" +
	"\fConcoxPacket\x12\x19\n" +
	"\braw_data\x18\x01 \x01(\fR\arawData\"(\n" +
	"\vHowenPacket\x12\x19\n" +
	"\braw_data\x18\x01 \x01(\fR\arawData\")\n" +
	"\fAquilaPacket\x12\x19\n" +
	"\braw_data\x18\x01 \x01(\fR\arawData\".\n" +
	"\x11IntellitracPacket\x12\x19\n" +
	"\braw_data\x18\x01 \x01(\fR\arawData\"+\n" +
	"\x0eQueclinkPacket\x12\x19\n" +
	"\braw_data\x18\x01 \x01(\fR\arawData\"@\n" +
	"\x0eDeviceResponse\x12\x12\n" +
	"\x04imei\x18\x01 \x01(\tR\x04imei\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\"-\n" +
	"\x17FetchDeviceModelRequest\x12\x12\n" +
	"\x04imei\x18\x01 \x01(\tR\x04imei\"0\n" +
	"\x18FetchDeviceModelResponse\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model*\x83\x01\n" +
	"\n" +
	"DeviceType\x12\r\n" +
	"\tTELTONIKA\x10\x00\x12\n" +
	"\n" +
	"\x06WANWAY\x10\x01\x12\n" +
	"\n" +
	"\x06CONCOX\x10\x02\x12\t\n" +
	"\x05HOWEN\x10\x03\x12\n" +
	"\n" +
	"\x06AQUILA\x10\x04\x12\x0f\n" +
	"\vINTELLITRAC\x10\x05\x12\x12\n" +
	"\x0eQUECLINK_GV200\x10\x06\x12\x12\n" +
	"\x0eQUECLINK_GT500\x10\a*o\n" +
	"\x12DeviceProtocolType\x12\n" +
	"\n" +
	"\x06FM1200\x10\x00\x12\b\n" +
	"\x04GT06\x10\x01\x12\b\n" +
	"\x04TR06\x10\x02\x12\v\n" +
	"\aHOWENWS\x10\x03\x12\v\n" +
	"\aOBDII2G\x10\x04\x12\x11\n" +
	"\rINTELLITRAC_A\x10\x05\x12\f\n" +
	"\bQUECLINK\x10\x06B7Z5github.com/404minds/avl-receiver/internal/types;typesb\x06proto3"

var (
	file_common_types_proto_rawDescOnce sync.Once
	file_common_types_proto_rawDescData []byte
)

func file_common_types_proto_rawDescGZIP() []byte {
	file_common_types_proto_rawDescOnce.Do(func() {
		file_common_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_types_proto_rawDesc), len(file_common_types_proto_rawDesc)))
	})
	return file_common_types_proto_rawDescData
}

var file_common_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_types_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_common_types_proto_goTypes = []any{
	(DeviceType)(0),                  // 0: types.DeviceType
	(DeviceProtocolType)(0),          // 1: types.DeviceProtocolType
	(*DeviceStatus)(nil),             // 2: types.DeviceStatus
	(*GPSPosition)(nil),              // 3: types.GPSPosition
	(*VehicleStatus)(nil),            // 4: types.VehicleStatus
	(*WanwayPacket)(nil),             // 5: types.WanwayPacket
	(*TeltonikaPacket)(nil),          // 6: types.TeltonikaPacket
	(*ConcoxPacket)(nil),             // 7: types.ConcoxPacket
	(*HowenPacket)(nil),              // 8: types.HowenPacket
	(*AquilaPacket)(nil),             // 9: types.AquilaPacket
	(*IntellitracPacket)(nil),        // 10: types.IntellitracPacket
	(*QueclinkPacket)(nil),           // 11: types.QueclinkPacket
	(*DeviceResponse)(nil),           // 12: types.DeviceResponse
	(*FetchDeviceModelRequest)(nil),  // 13: types.FetchDeviceModelRequest
	(*FetchDeviceModelResponse)(nil), // 14: types.FetchDeviceModelResponse
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
}
var file_common_types_proto_depIdxs = []int32{
	0,  // 0: types.DeviceStatus.device_type:type_name -> types.DeviceType
	15, // 1: types.DeviceStatus.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 2: types.DeviceStatus.position:type_name -> types.GPSPosition
	4,  // 3: types.DeviceStatus.vehicle_status:type_name -> types.VehicleStatus
	5,  // 4: types.DeviceStatus.wanway_packet:type_name -> types.WanwayPacket
	6,  // 5: types.DeviceStatus.teltonika_packet:type_name -> types.TeltonikaPacket
	7,  // 6: types.DeviceStatus.concox_packet:type_name -> types.ConcoxPacket
	8,  // 7: types.DeviceStatus.howen_packet:type_name -> types.HowenPacket
	9,  // 8: types.DeviceStatus.aquila_packet:type_name -> types.AquilaPacket
	10, // 9: types.DeviceStatus.intellitrac_packet:type_name -> types.IntellitracPacket
	11, // 10: types.DeviceStatus.queclink_packet:type_name -> types.QueclinkPacket
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_common_types_proto_init() }
func file_common_types_proto_init() {
	if File_common_types_proto != nil {
		return
	}
	file_common_types_proto_msgTypes[0].OneofWrappers = []any{
		(*DeviceStatus_WanwayPacket)(nil),
		(*DeviceStatus_TeltonikaPacket)(nil),
		(*DeviceStatus_ConcoxPacket)(nil),
		(*DeviceStatus_HowenPacket)(nil),
		(*DeviceStatus_AquilaPacket)(nil),
		(*DeviceStatus_IntellitracPacket)(nil),
		(*DeviceStatus_QueclinkPacket)(nil),
	}
	file_common_types_proto_msgTypes[1].OneofWrappers = []any{}
	file_common_types_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_types_proto_rawDesc), len(file_common_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_proto_goTypes,
		DependencyIndexes: file_common_types_proto_depIdxs,
		EnumInfos:         file_common_types_proto_enumTypes,
		MessageInfos:      file_common_types_proto_msgTypes,
	}.Build()
	File_common_types_proto = out.File
	file_common_types_proto_goTypes = nil
	file_common_types_proto_depIdxs = nil
}
