services:
  avl-receiver:
    build:
      context: .
    image: avl-receiver
    container_name: avl-receiver
    networks:
      - deployment_base-network
    ports:
      - "21000:21000" # TCP server port
      - "15000:15000" # gRPC server port
    command: ["./receiver", "-port", "21000", "-grpcPort", "15000", "-remoteStoreAddr", "carbuddy-consumer:9000"]
    

networks:
  deployment_base-network:
    external: true
