services:
  avl-receiver:
    build:
      context: .
    image: avl-receiver
    container_name: avl-receiver
    networks:
      - deployment_base-network
    restart: on-failure
    ports:
      - "21000:21000" # TCP server port
      - "15000:15000" # gRPC server port
    environment:
      - REMOTE_STORE_ADDR=${CUSTOM_REMOTE_STORE_ADDR}
      - GRPC_SERVICE_NAME=${CUSTOM_GRPC_SERVICE_NAME}

networks:
  deployment_base-network:
    external: true
