services:
  avl-receiver:
    build:
      context: .
    image: avl-receiver
    container_name: avl-receiver
    networks:
      - deployment_base-network
    ports:
      - "21000:21000"
    command: ["./receiver", "-port", "21000", "-remoteStoreAddr", "fns-consumer-grpc-server:8000"]

networks:
  deployment_base-network:
   external: true
