// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: avl-service.proto

package store

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AvlReceiverServiceClient is the client API for AvlReceiverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AvlReceiverServiceClient interface {
	SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error)
}

type avlReceiverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAvlReceiverServiceClient(cc grpc.ClientConnInterface) AvlReceiverServiceClient {
	return &avlReceiverServiceClient{cc}
}

func (c *avlReceiverServiceClient) SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error) {
	out := new(SendCommandResponse)
	err := c.cc.Invoke(ctx, "/store.AvlReceiverService/SendCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AvlReceiverServiceServer is the server API for AvlReceiverService service.
// All implementations must embed UnimplementedAvlReceiverServiceServer
// for forward compatibility
type AvlReceiverServiceServer interface {
	SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error)
	mustEmbedUnimplementedAvlReceiverServiceServer()
}

// UnimplementedAvlReceiverServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAvlReceiverServiceServer struct {
}

func (UnimplementedAvlReceiverServiceServer) SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedAvlReceiverServiceServer) mustEmbedUnimplementedAvlReceiverServiceServer() {}

// UnsafeAvlReceiverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvlReceiverServiceServer will
// result in compilation errors.
type UnsafeAvlReceiverServiceServer interface {
	mustEmbedUnimplementedAvlReceiverServiceServer()
}

func RegisterAvlReceiverServiceServer(s grpc.ServiceRegistrar, srv AvlReceiverServiceServer) {
	s.RegisterService(&AvlReceiverService_ServiceDesc, srv)
}

func _AvlReceiverService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvlReceiverServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.AvlReceiverService/SendCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvlReceiverServiceServer).SendCommand(ctx, req.(*SendCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AvlReceiverService_ServiceDesc is the grpc.ServiceDesc for AvlReceiverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AvlReceiverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "store.AvlReceiverService",
	HandlerType: (*AvlReceiverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommand",
			Handler:    _AvlReceiverService_SendCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avl-service.proto",
}
